library(shinytest2)

test_that("{shinytest2} recording: shiny22", {
  local_app_support(test_path("../../inst/shiny"))
  app <- AppDriver$new(test_path("../../inst/shiny"), variant = platform_variant(),
      name = "shiny22", height = 752, width = 1139)
  app$expect_screenshot()
  app$click("test_data")
  app$click("run")
  app$expect_screenshot()
  app$set_inputs(degree = 4)
  app$set_inputs(curve_color = "#FF0084")
  app$click("apply_color")
  app$click("run")
  app$expect_screenshot()
  app$click("run")
  app$set_inputs(degree = 3)
  app$set_inputs(degree = 2)
  app$set_inputs(degree = 1)
  app$set_inputs(curve_color = "#FF1500")
  app$click("apply_color")
  app$expect_screenshot()
  app$click("run")
  app$set_inputs(degree = 2)
  app$set_inputs(curve_color = "#00FF0D")
  app$click("apply_color")
  app$click("run")
  app$expect_screenshot()
  app$click("run")
  app$expect_screenshot()
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$set_inputs(monot = "1")
  app$set_inputs(degree = 1)
  app$click("run")
  app$set_inputs(monot = "-1")
  app$expect_screenshot()
  app$set_inputs(monot = "0")
  app$set_inputs(conv = "1")
  app$set_inputs(conv = "0")
  app$set_inputs(degree = 2)
  app$set_inputs(monot = "1")
  app$set_inputs(curve_color = "#0F9417")
  app$click("apply_color")
  app$click("run")
  app$expect_screenshot()
  app$set_inputs(degree = 3)
  app$set_inputs(curve_color = "#06470A")
  app$click("apply_color")
  app$click("run")
  app$expect_screenshot()
  app$set_inputs(degree = 4)
  app$set_inputs(curve_color = "#A8B3A9")
  app$click("run")
  app$expect_screenshot()
  app$set_inputs(monot = "0")
  app$set_inputs(monot = "-1")
  app$click("run")
  app$expect_screenshot()
  app$set_inputs(monot = "0")
  app$set_inputs(conv = "1")
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("generate_custom")
  app$click("run")
  app$set_inputs(degree = 3)
  app$set_inputs(curve_color = "#576158")
  app$click("apply_color")
  app$click("run")
  app$expect_screenshot()
  app$set_inputs(degree = 2)
  app$set_inputs(degree = 1)
  app$set_inputs(degree = 2)
  app$set_inputs(curve_color = "#121412")
  app$click("run")
  app$expect_screenshot()
  app$click("clear_curves")
  app$click("clear_curves")
  app$click("clear_curves")
  app$expect_screenshot()
  app$click("temp_data")
  app$click("run")
  app$expect_screenshot()
  app$expect_values()
  app$set_inputs(degree = 1)
  app$click("run")
  app$expect_screenshot()
  app$expect_values()
  app$set_inputs(degree = 2)
  app$set_inputs(degree = 3)
  app$click("run")
  app$expect_screenshot()
  app$expect_values()
  app$set_inputs(degree = 4)
  app$expect_screenshot()
  app$expect_values()
  app$set_inputs(conv = "0")
  app$click("clear_knots")
  app$set_inputs(knots_count = 3)
  app$set_inputs(knots_count = 4)
  app$set_inputs(constraint_mode = "region")
  app$click("start_selection")
  app$click("start_selection")
  app$click("clear_regions")
  app$click("start_selection")
  app$click("start_selection")
  app$set_inputs(region_monot = "1")
  app$click("add_region")
  app$expect_values()
  app$expect_screenshot()

})
